// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { AuthService } from "./api/resources/auth/service/AuthService";

export function register(
    honoApp: Hono,
    services: {
        auth: AuthService;
    },
): void {
    honoApp.route("/", services.auth.toHono());
}
