// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { OrganizationService } from "./api/resources/organization/service/OrganizationService";
import type { UserService } from "./api/resources/user/service/UserService";

export function register(
    honoApp: Hono,
    services: {
        organization: OrganizationService;
        user: UserService;
    },
): void {
    honoApp.route("/organizations", services.organization.toHono());
    honoApp.route("/users", services.user.toHono());
    honoApp.route("/users/events", services.user.events.toHono());
    honoApp.route("/users/events/metadata", services.user.events.metadata.toHono());
}
