// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { ComplexService } from "./api/resources/complex/service/ComplexService";
import type { InlineUsersService as inlineUsers_InlineUsersService } from "./api/resources/inlineUsers/resources/inlineUsers/service/InlineUsersService";
import type { UsersService } from "./api/resources/users/service/UsersService";

export function register(
    honoApp: Hono,
    services: {
        complex: ComplexService;
        users: UsersService;
        inlineUsers: {
            inlineUsers: inlineUsers_InlineUsersService;
        };
    },
): void {
    honoApp.route("", services.complex.toHono());
    honoApp.route("/inline-users", services.inlineUsers.inlineUsers.toHono());
    honoApp.route("/users", services.users.toHono());
}
