// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { PropertyBasedErrorService } from "./api/resources/propertyBasedError/service/PropertyBasedErrorService";

export function register(
    honoApp: Hono,
    services: {
        propertyBasedError: PropertyBasedErrorService;
    },
): void {
    honoApp.route("", services.propertyBasedError.toHono());
}
