// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { PaymentService } from "./api/resources/payment/service/PaymentService";

export function register(
    honoApp: Hono,
    services: {
        payment: PaymentService;
    },
): void {
    honoApp.route("/payment", services.payment.toHono());
}
