// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { ServiceService } from "./api/resources/service/service/ServiceService";

export function register(
    honoApp: Hono,
    services: {
        service: ServiceService;
    },
): void {
    honoApp.route("/container", services.service.toHono());
}
