// This file was auto-generated by Fern from our API Definition.

import { Hono, type MiddlewareHandler } from "hono";
import { setCookie } from "hono/cookie";
import type { CookieOptions } from "hono/utils/cookie";
import * as errors from "../../../../errors/index";
import * as serializers from "../../../../serialization/index";
import type * as SeedTrace from "../../../index";

export interface PlaylistServiceMethods {
    /**
     * Create a new playlist
     */
    createPlaylist(
        req: {
            params: {
                serviceParam: number;
            };
            query: {
                datetime: Date;
                optionalDatetime?: Date;
            };
            body: SeedTrace.PlaylistCreateRequest;
        },
        res: {
            send: (responseBody: SeedTrace.Playlist) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    /**
     * Returns the user's playlists
     */
    getPlaylists(
        req: {
            params: {
                serviceParam: number;
            };
            query: {
                limit?: number;
                otherField: string;
                multiLineDocs: string;
                optionalMultipleField?: string;
                multipleField: string;
            };
        },
        res: {
            send: (responseBody: SeedTrace.Playlist[]) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    /**
     * Returns a playlist
     */
    getPlaylist(
        req: {
            params: {
                serviceParam: number;
                playlistId: serializers.PlaylistId.Raw;
            };
        },
        res: {
            send: (responseBody: SeedTrace.Playlist) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    /**
     * Updates a playlist
     */
    updatePlaylist(
        req: {
            params: {
                serviceParam: number;
                playlistId: serializers.PlaylistId.Raw;
            };
            body: SeedTrace.UpdatePlaylistRequest | undefined;
        },
        res: {
            send: (responseBody: SeedTrace.Playlist | undefined) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    /**
     * Deletes a playlist
     */
    deletePlaylist(
        req: {
            params: {
                serviceParam: number;
                playlist_id: serializers.PlaylistId.Raw;
            };
        },
        res: {
            send: () => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
}

export class PlaylistService {
    private app;

    constructor(
        private readonly methods: PlaylistServiceMethods,
        middleware: MiddlewareHandler[] = [],
    ) {
        this.app = new Hono();
        middleware.forEach((m) => this.app.use("*", m));
    }

    /** Adds middleware to the Hono app for all routes. */
    public addMiddleware(handler: MiddlewareHandler): this {
        this.app.use("*", handler);
        return this;
    }

    /** Returns the Hono app instance with all routes configured. */
    public toHono(): Hono {
        this.app.post("/create", async (c) => {
            const request = serializers.PlaylistCreateRequest.parse(await c.req.json());
            if (request.ok) {
                try {
                    let _responseBody: SeedTrace.Playlist | undefined;
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.createPlaylist(
                        {
                            params: c.req.param(),
                            query: c.req.query(),
                            body: request.value,
                        },
                        {
                            send: async (responseBody) => {
                                _responseBody = responseBody;
                            },
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.json(
                        serializers.Playlist.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }),
                        200,
                    );
                } catch (error) {
                    if (error instanceof errors.SeedTraceError) {
                        console.warn(
                            `Endpoint 'createPlaylist' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.get("/all", async (c) => {
            try {
                let _responseBody: SeedTrace.Playlist[] | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.getPlaylists(
                    {
                        params: c.req.param(),
                        query: c.req.query(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(_responseBody, 200);
            } catch (error) {
                if (error instanceof errors.SeedTraceError) {
                    console.warn(
                        `Endpoint 'getPlaylists' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        this.app.get("/:playlistId", async (c) => {
            try {
                let _responseBody: SeedTrace.Playlist | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.getPlaylist(
                    {
                        params: c.req.param(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(
                    serializers.Playlist.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }),
                    200,
                );
            } catch (error) {
                if (error instanceof errors.SeedTraceError) {
                    switch (error.errorName) {
                        case "PlaylistIdNotFoundError":
                        case "UnauthorizedError":
                            break;
                        default:
                            console.warn(
                                `Endpoint 'getPlaylist' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                            );
                    }
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        this.app.put("/:playlistId", async (c) => {
            const request = await c.req.json();
            if (request.ok) {
                try {
                    let _responseBody: (SeedTrace.Playlist | undefined) | undefined;
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.updatePlaylist(
                        {
                            params: c.req.param(),
                            body: request.value,
                        },
                        {
                            send: async (responseBody) => {
                                _responseBody = responseBody;
                            },
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.json(_responseBody, 200);
                } catch (error) {
                    if (error instanceof errors.SeedTraceError) {
                        switch (error.errorName) {
                            case "PlaylistIdNotFoundError":
                                break;
                            default:
                                console.warn(
                                    `Endpoint 'updatePlaylist' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                                );
                        }
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.delete("/:playlist_id", async (c) => {
            try {
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.deletePlaylist(
                    {
                        params: c.req.param(),
                    },
                    {
                        send: async () => {},
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.text("", 204);
            } catch (error) {
                if (error instanceof errors.SeedTraceError) {
                    console.warn(
                        `Endpoint 'deletePlaylist' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        return this.app;
    }
}
