// This file was auto-generated by Fern from our API Definition.

import type { Context } from "hono";
import * as errors from "../../../../errors/index";
import * as serializers from "../../../../serialization/index";
import type * as SeedBasicAuth from "../../../index";

export class UnauthorizedRequest extends errors.SeedBasicAuthError {
    constructor(private readonly body: SeedBasicAuth.UnauthorizedRequestErrorBody) {
        super("UnauthorizedRequest");
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = this.constructor.name;
    }

    public toResponse(c: Context): Response {
        return c.json(
            serializers.UnauthorizedRequestErrorBody.jsonOrThrow(this.body, { unrecognizedObjectKeys: "strip" }),
            401,
        );
    }
}
