// This file was auto-generated by Fern from our API Definition.

import { Hono, type MiddlewareHandler } from "hono";
import { setCookie } from "hono/cookie";
import type { CookieOptions } from "hono/utils/cookie";
import * as errors from "../../errors/index";
import * as serializers from "../../serialization/index";
import type * as SeedApi from "../index";

export interface RootServiceMethods {
    /**
     * Returns a RootObject which inherits from a nullable schema.
     */
    getTest(
        req: {},
        res: {
            send: (responseBody: SeedApi.RootObject) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    /**
     * Creates a test object with nullable allOf in request body.
     */
    createTest(
        req: {
            body: SeedApi.RootObject;
        },
        res: {
            send: (responseBody: SeedApi.RootObject) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
}

export class RootService {
    private app;

    constructor(
        private readonly methods: RootServiceMethods,
        middleware: MiddlewareHandler[] = [],
    ) {
        this.app = new Hono();
        middleware.forEach((m) => this.app.use("*", m));
    }

    /** Adds middleware to the Hono app for all routes. */
    public addMiddleware(handler: MiddlewareHandler): this {
        this.app.use("*", handler);
        return this;
    }

    /** Returns the Hono app instance with all routes configured. */
    public toHono(): Hono {
        this.app.get("/test", async (c) => {
            try {
                let _responseBody: SeedApi.RootObject | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.getTest(
                    {},
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(
                    serializers.RootObject.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }),
                    200,
                );
            } catch (error) {
                if (error instanceof errors.SeedApiError) {
                    console.warn(
                        `Endpoint 'getTest' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        this.app.post("/test", async (c) => {
            const request = serializers.RootObject.parse(await c.req.json());
            if (request.ok) {
                try {
                    let _responseBody: SeedApi.RootObject | undefined;
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.createTest(
                        {
                            body: request.value,
                        },
                        {
                            send: async (responseBody) => {
                                _responseBody = responseBody;
                            },
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.json(
                        serializers.RootObject.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }),
                        200,
                    );
                } catch (error) {
                    if (error instanceof errors.SeedApiError) {
                        console.warn(
                            `Endpoint 'createTest' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        return this.app;
    }
}
