// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { AdminService } from "./api/resources/admin/service/AdminService";
import type { HomepageService } from "./api/resources/homepage/service/HomepageService";
import type { MigrationService } from "./api/resources/migration/service/MigrationService";
import type { PlaylistService } from "./api/resources/playlist/service/PlaylistService";
import type { ProblemService } from "./api/resources/problem/service/ProblemService";
import type { SubmissionService } from "./api/resources/submission/service/SubmissionService";
import type { SyspropService } from "./api/resources/sysprop/service/SyspropService";
import type { ProblemService as v2_ProblemService } from "./api/resources/v2/resources/problem/service/ProblemService";
import type { ProblemService as v2_v3_ProblemService } from "./api/resources/v2/resources/v3/resources/problem/service/ProblemService";
import type { V2Service as v2_RootService } from "./api/resources/v2/service/V2Service";

export function register(
    honoApp: Hono,
    services: {
        admin: AdminService;
        homepage: HomepageService;
        migration: MigrationService;
        playlist: PlaylistService;
        problem: ProblemService;
        submission: SubmissionService;
        sysprop: SyspropService;
        v2: {
            _root: v2_RootService;
            problem: v2_ProblemService;
            v3: {
                problem: v2_v3_ProblemService;
            };
        };
    },
): void {
    honoApp.route("/", services.v2._root.toHono());
    honoApp.route("/admin", services.admin.toHono());
    honoApp.route("/homepage-problems", services.homepage.toHono());
    honoApp.route("/migration-info", services.migration.toHono());
    honoApp.route("/v2/playlist/:serviceParam", services.playlist.toHono());
    honoApp.route("/problem-crud", services.problem.toHono());
    honoApp.route("/sessions", services.submission.toHono());
    honoApp.route("/sysprop", services.sysprop.toHono());
    honoApp.route("/problems-v2", services.v2.problem.toHono());
    honoApp.route("/problems-v2", services.v2.v3.problem.toHono());
}
