// This file was auto-generated by Fern from our API Definition.

import { Hono, type MiddlewareHandler } from "hono";
import { setCookie } from "hono/cookie";
import type { CookieOptions } from "hono/utils/cookie";
import * as errors from "../../../../../../errors/index";
import * as serializers from "../../../../../../serialization/index";
import type * as SeedPagination from "../../../../../index";

export interface InlineUsersServiceMethods {
    listWithCursorPagination(
        req: {
            query: {
                page?: number;
                per_page?: number;
                order?: SeedPagination.inlineUsers.Order;
                starting_after?: string;
            };
        },
        res: {
            send: (responseBody: SeedPagination.inlineUsers.ListUsersPaginationResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    listWithMixedTypeCursorPagination(
        req: {
            query: {
                cursor?: string;
            };
        },
        res: {
            send: (responseBody: SeedPagination.inlineUsers.ListUsersMixedTypePaginationResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    listWithBodyCursorPagination(
        req: {
            body: SeedPagination.inlineUsers.ListUsersBodyCursorPaginationRequest;
        },
        res: {
            send: (responseBody: SeedPagination.inlineUsers.ListUsersPaginationResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    listWithOffsetPagination(
        req: {
            query: {
                page?: number;
                per_page?: number;
                order?: SeedPagination.inlineUsers.Order;
                starting_after?: string;
            };
        },
        res: {
            send: (responseBody: SeedPagination.inlineUsers.ListUsersPaginationResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    listWithDoubleOffsetPagination(
        req: {
            query: {
                page?: number;
                per_page?: number;
                order?: SeedPagination.inlineUsers.Order;
                starting_after?: string;
            };
        },
        res: {
            send: (responseBody: SeedPagination.inlineUsers.ListUsersPaginationResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    listWithBodyOffsetPagination(
        req: {
            body: SeedPagination.inlineUsers.ListUsersBodyOffsetPaginationRequest;
        },
        res: {
            send: (responseBody: SeedPagination.inlineUsers.ListUsersPaginationResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    listWithOffsetStepPagination(
        req: {
            query: {
                page?: number;
                limit?: number;
                order?: SeedPagination.inlineUsers.Order;
            };
        },
        res: {
            send: (responseBody: SeedPagination.inlineUsers.ListUsersPaginationResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    listWithOffsetPaginationHasNextPage(
        req: {
            query: {
                page?: number;
                limit?: number;
                order?: SeedPagination.inlineUsers.Order;
            };
        },
        res: {
            send: (responseBody: SeedPagination.inlineUsers.ListUsersPaginationResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    listWithExtendedResults(
        req: {
            query: {
                cursor?: string;
            };
        },
        res: {
            send: (responseBody: SeedPagination.inlineUsers.ListUsersExtendedResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    listWithExtendedResultsAndOptionalData(
        req: {
            query: {
                cursor?: string;
            };
        },
        res: {
            send: (responseBody: SeedPagination.inlineUsers.ListUsersExtendedOptionalListResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    listUsernames(
        req: {
            query: {
                starting_after?: string;
            };
        },
        res: {
            send: (responseBody: SeedPagination.UsernameCursor) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    listWithGlobalConfig(
        req: {
            query: {
                offset?: number;
            };
        },
        res: {
            send: (responseBody: SeedPagination.inlineUsers.UsernameContainer) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
}

export class InlineUsersService {
    private app;

    constructor(
        private readonly methods: InlineUsersServiceMethods,
        middleware: MiddlewareHandler[] = [],
    ) {
        this.app = new Hono();
        middleware.forEach((m) => this.app.use("*", m));
    }

    /** Adds middleware to the Hono app for all routes. */
    public addMiddleware(handler: MiddlewareHandler): this {
        this.app.use("*", handler);
        return this;
    }

    /** Returns the Hono app instance with all routes configured. */
    public toHono(): Hono {
        this.app.get("", async (c) => {
            try {
                let _responseBody: SeedPagination.inlineUsers.ListUsersPaginationResponse | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.listWithCursorPagination(
                    {
                        query: c.req.query(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(
                    serializers.inlineUsers.ListUsersPaginationResponse.jsonOrThrow(_responseBody, {
                        unrecognizedObjectKeys: "strip",
                    }),
                    200,
                );
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listWithCursorPagination' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        this.app.post("", async (c) => {
            try {
                let _responseBody: SeedPagination.inlineUsers.ListUsersMixedTypePaginationResponse | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.listWithMixedTypeCursorPagination(
                    {
                        query: c.req.query(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(
                    serializers.inlineUsers.ListUsersMixedTypePaginationResponse.jsonOrThrow(_responseBody, {
                        unrecognizedObjectKeys: "strip",
                    }),
                    200,
                );
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listWithMixedTypeCursorPagination' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        this.app.post("", async (c) => {
            const request = await c.req.json();
            if (request.ok) {
                try {
                    let _responseBody: SeedPagination.inlineUsers.ListUsersPaginationResponse | undefined;
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.listWithBodyCursorPagination(
                        {
                            body: request.value,
                        },
                        {
                            send: async (responseBody) => {
                                _responseBody = responseBody;
                            },
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.json(
                        serializers.inlineUsers.ListUsersPaginationResponse.jsonOrThrow(_responseBody, {
                            unrecognizedObjectKeys: "strip",
                        }),
                        200,
                    );
                } catch (error) {
                    if (error instanceof errors.SeedPaginationError) {
                        console.warn(
                            `Endpoint 'listWithBodyCursorPagination' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.get("", async (c) => {
            try {
                let _responseBody: SeedPagination.inlineUsers.ListUsersPaginationResponse | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.listWithOffsetPagination(
                    {
                        query: c.req.query(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(
                    serializers.inlineUsers.ListUsersPaginationResponse.jsonOrThrow(_responseBody, {
                        unrecognizedObjectKeys: "strip",
                    }),
                    200,
                );
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listWithOffsetPagination' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        this.app.get("", async (c) => {
            try {
                let _responseBody: SeedPagination.inlineUsers.ListUsersPaginationResponse | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.listWithDoubleOffsetPagination(
                    {
                        query: c.req.query(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(
                    serializers.inlineUsers.ListUsersPaginationResponse.jsonOrThrow(_responseBody, {
                        unrecognizedObjectKeys: "strip",
                    }),
                    200,
                );
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listWithDoubleOffsetPagination' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        this.app.post("", async (c) => {
            const request = await c.req.json();
            if (request.ok) {
                try {
                    let _responseBody: SeedPagination.inlineUsers.ListUsersPaginationResponse | undefined;
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.listWithBodyOffsetPagination(
                        {
                            body: request.value,
                        },
                        {
                            send: async (responseBody) => {
                                _responseBody = responseBody;
                            },
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.json(
                        serializers.inlineUsers.ListUsersPaginationResponse.jsonOrThrow(_responseBody, {
                            unrecognizedObjectKeys: "strip",
                        }),
                        200,
                    );
                } catch (error) {
                    if (error instanceof errors.SeedPaginationError) {
                        console.warn(
                            `Endpoint 'listWithBodyOffsetPagination' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.get("", async (c) => {
            try {
                let _responseBody: SeedPagination.inlineUsers.ListUsersPaginationResponse | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.listWithOffsetStepPagination(
                    {
                        query: c.req.query(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(
                    serializers.inlineUsers.ListUsersPaginationResponse.jsonOrThrow(_responseBody, {
                        unrecognizedObjectKeys: "strip",
                    }),
                    200,
                );
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listWithOffsetStepPagination' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        this.app.get("", async (c) => {
            try {
                let _responseBody: SeedPagination.inlineUsers.ListUsersPaginationResponse | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.listWithOffsetPaginationHasNextPage(
                    {
                        query: c.req.query(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(
                    serializers.inlineUsers.ListUsersPaginationResponse.jsonOrThrow(_responseBody, {
                        unrecognizedObjectKeys: "strip",
                    }),
                    200,
                );
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listWithOffsetPaginationHasNextPage' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        this.app.get("", async (c) => {
            try {
                let _responseBody: SeedPagination.inlineUsers.ListUsersExtendedResponse | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.listWithExtendedResults(
                    {
                        query: c.req.query(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(
                    serializers.inlineUsers.ListUsersExtendedResponse.jsonOrThrow(_responseBody, {
                        unrecognizedObjectKeys: "strip",
                    }),
                    200,
                );
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listWithExtendedResults' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        this.app.get("", async (c) => {
            try {
                let _responseBody: SeedPagination.inlineUsers.ListUsersExtendedOptionalListResponse | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.listWithExtendedResultsAndOptionalData(
                    {
                        query: c.req.query(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(
                    serializers.inlineUsers.ListUsersExtendedOptionalListResponse.jsonOrThrow(_responseBody, {
                        unrecognizedObjectKeys: "strip",
                    }),
                    200,
                );
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listWithExtendedResultsAndOptionalData' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        this.app.get("", async (c) => {
            try {
                let _responseBody: SeedPagination.UsernameCursor | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.listUsernames(
                    {
                        query: c.req.query(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(
                    serializers.UsernameCursor.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }),
                    200,
                );
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listUsernames' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        this.app.get("", async (c) => {
            try {
                let _responseBody: SeedPagination.inlineUsers.UsernameContainer | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.listWithGlobalConfig(
                    {
                        query: c.req.query(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(
                    serializers.inlineUsers.UsernameContainer.jsonOrThrow(_responseBody, {
                        unrecognizedObjectKeys: "strip",
                    }),
                    200,
                );
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listWithGlobalConfig' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        return this.app;
    }
}
