// This file was auto-generated by Fern from our API Definition.

import { Hono, type MiddlewareHandler } from "hono";
import { setCookie } from "hono/cookie";
import type { CookieOptions } from "hono/utils/cookie";
import * as errors from "../../../../errors/index";
import * as serializers from "../../../../serialization/index";
import type * as SeedTrace from "../../../index";

export interface AdminServiceMethods {
    updateTestSubmissionStatus(
        req: {
            params: {
                submissionId: serializers.SubmissionId.Raw;
            };
            body: SeedTrace.TestSubmissionStatus;
        },
        res: {
            send: () => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    sendTestSubmissionUpdate(
        req: {
            params: {
                submissionId: serializers.SubmissionId.Raw;
            };
            body: SeedTrace.TestSubmissionUpdate;
        },
        res: {
            send: () => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    updateWorkspaceSubmissionStatus(
        req: {
            params: {
                submissionId: serializers.SubmissionId.Raw;
            };
            body: SeedTrace.WorkspaceSubmissionStatus;
        },
        res: {
            send: () => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    sendWorkspaceSubmissionUpdate(
        req: {
            params: {
                submissionId: serializers.SubmissionId.Raw;
            };
            body: SeedTrace.WorkspaceSubmissionUpdate;
        },
        res: {
            send: () => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    storeTracedTestCase(
        req: {
            params: {
                submissionId: serializers.SubmissionId.Raw;
                testCaseId: string;
            };
            body: SeedTrace.StoreTracedTestCaseRequest;
        },
        res: {
            send: () => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    storeTracedTestCaseV2(
        req: {
            params: {
                submissionId: serializers.SubmissionId.Raw;
                testCaseId: serializers.v2.TestCaseId.Raw;
            };
            body: SeedTrace.TraceResponseV2[];
        },
        res: {
            send: () => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    storeTracedWorkspace(
        req: {
            params: {
                submissionId: serializers.SubmissionId.Raw;
            };
            body: SeedTrace.StoreTracedWorkspaceRequest;
        },
        res: {
            send: () => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    storeTracedWorkspaceV2(
        req: {
            params: {
                submissionId: serializers.SubmissionId.Raw;
            };
            body: SeedTrace.TraceResponseV2[];
        },
        res: {
            send: () => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
}

export class AdminService {
    private app;

    constructor(
        private readonly methods: AdminServiceMethods,
        middleware: MiddlewareHandler[] = [],
    ) {
        this.app = new Hono();
        middleware.forEach((m) => this.app.use("*", m));
    }

    /** Adds middleware to the Hono app for all routes. */
    public addMiddleware(handler: MiddlewareHandler): this {
        this.app.use("*", handler);
        return this;
    }

    /** Returns the Hono app instance with all routes configured. */
    public toHono(): Hono {
        this.app.post("/store-test-submission-status/:submissionId", async (c) => {
            const request = serializers.TestSubmissionStatus.parse(await c.req.json());
            if (request.ok) {
                try {
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.updateTestSubmissionStatus(
                        {
                            params: c.req.param(),
                            body: request.value,
                        },
                        {
                            send: async () => {},
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.text("", 204);
                } catch (error) {
                    if (error instanceof errors.SeedTraceError) {
                        console.warn(
                            `Endpoint 'updateTestSubmissionStatus' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.post("/store-test-submission-status-v2/:submissionId", async (c) => {
            const request = serializers.TestSubmissionUpdate.parse(await c.req.json());
            if (request.ok) {
                try {
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.sendTestSubmissionUpdate(
                        {
                            params: c.req.param(),
                            body: request.value,
                        },
                        {
                            send: async () => {},
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.text("", 204);
                } catch (error) {
                    if (error instanceof errors.SeedTraceError) {
                        console.warn(
                            `Endpoint 'sendTestSubmissionUpdate' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.post("/store-workspace-submission-status/:submissionId", async (c) => {
            const request = serializers.WorkspaceSubmissionStatus.parse(await c.req.json());
            if (request.ok) {
                try {
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.updateWorkspaceSubmissionStatus(
                        {
                            params: c.req.param(),
                            body: request.value,
                        },
                        {
                            send: async () => {},
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.text("", 204);
                } catch (error) {
                    if (error instanceof errors.SeedTraceError) {
                        console.warn(
                            `Endpoint 'updateWorkspaceSubmissionStatus' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.post("/store-workspace-submission-status-v2/:submissionId", async (c) => {
            const request = serializers.WorkspaceSubmissionUpdate.parse(await c.req.json());
            if (request.ok) {
                try {
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.sendWorkspaceSubmissionUpdate(
                        {
                            params: c.req.param(),
                            body: request.value,
                        },
                        {
                            send: async () => {},
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.text("", 204);
                } catch (error) {
                    if (error instanceof errors.SeedTraceError) {
                        console.warn(
                            `Endpoint 'sendWorkspaceSubmissionUpdate' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.post("/store-test-trace/submission/:submissionId/testCase/:testCaseId", async (c) => {
            const request = await c.req.json();
            if (request.ok) {
                try {
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.storeTracedTestCase(
                        {
                            params: c.req.param(),
                            body: request.value,
                        },
                        {
                            send: async () => {},
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.text("", 204);
                } catch (error) {
                    if (error instanceof errors.SeedTraceError) {
                        console.warn(
                            `Endpoint 'storeTracedTestCase' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.post("/store-test-trace-v2/submission/:submissionId/testCase/:testCaseId", async (c) => {
            const request = await c.req.json();
            if (request.ok) {
                try {
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.storeTracedTestCaseV2(
                        {
                            params: c.req.param(),
                            body: request.value,
                        },
                        {
                            send: async () => {},
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.text("", 204);
                } catch (error) {
                    if (error instanceof errors.SeedTraceError) {
                        console.warn(
                            `Endpoint 'storeTracedTestCaseV2' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.post("/store-workspace-trace/submission/:submissionId", async (c) => {
            const request = await c.req.json();
            if (request.ok) {
                try {
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.storeTracedWorkspace(
                        {
                            params: c.req.param(),
                            body: request.value,
                        },
                        {
                            send: async () => {},
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.text("", 204);
                } catch (error) {
                    if (error instanceof errors.SeedTraceError) {
                        console.warn(
                            `Endpoint 'storeTracedWorkspace' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.post("/store-workspace-trace-v2/submission/:submissionId", async (c) => {
            const request = await c.req.json();
            if (request.ok) {
                try {
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.storeTracedWorkspaceV2(
                        {
                            params: c.req.param(),
                            body: request.value,
                        },
                        {
                            send: async () => {},
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.text("", 204);
                } catch (error) {
                    if (error instanceof errors.SeedTraceError) {
                        console.warn(
                            `Endpoint 'storeTracedWorkspaceV2' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        return this.app;
    }
}
