// This file was auto-generated by Fern from our API Definition.

import type { Context } from "hono";
import * as errors from "../../../../errors/index";
import * as serializers from "../../../../serialization/index";
import type * as SeedTrace from "../../../index";

export class PlaylistIdNotFoundError extends errors.SeedTraceError {
    constructor(private readonly body: SeedTrace.PlaylistIdNotFoundErrorBody) {
        super("PlaylistIdNotFoundError");
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = this.constructor.name;
    }

    public toResponse(c: Context): Response {
        return c.json(
            serializers.PlaylistIdNotFoundErrorBody.jsonOrThrow(this.body, { unrecognizedObjectKeys: "strip" }),
            404,
        );
    }
}
