// This file was auto-generated by Fern from our API Definition.

import type { Context } from "hono";
import * as errors from "../../../../errors/index";

export class UnauthorizedError extends errors.SeedTraceError {
    constructor() {
        super("UnauthorizedError");
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = this.constructor.name;
    }

    public toResponse(c: Context): Response {
        return c.text("", 401);
    }
}
