// This file was auto-generated by Fern from our API Definition.

import { Hono, type MiddlewareHandler } from "hono";
import { setCookie } from "hono/cookie";
import type { CookieOptions } from "hono/utils/cookie";
import * as errors from "../../../../errors/index";
import type * as SeedMixedFileDirectory from "../../../index";

export interface UserServiceMethods {
    /**
     * List all users.
     */
    list(
        req: {
            query: {
                limit?: number;
            };
        },
        res: {
            send: (responseBody: SeedMixedFileDirectory.User[]) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
}

export class UserService {
    private app;

    constructor(
        private readonly methods: UserServiceMethods,
        middleware: MiddlewareHandler[] = [],
    ) {
        this.app = new Hono();
        middleware.forEach((m) => this.app.use("*", m));
    }

    /** Adds middleware to the Hono app for all routes. */
    public addMiddleware(handler: MiddlewareHandler): this {
        this.app.use("*", handler);
        return this;
    }

    /** Returns the Hono app instance with all routes configured. */
    public toHono(): Hono {
        this.app.get("/", async (c) => {
            try {
                let _responseBody: SeedMixedFileDirectory.User[] | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.list(
                    {
                        query: c.req.query(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(_responseBody, 200);
            } catch (error) {
                if (error instanceof errors.SeedMixedFileDirectoryError) {
                    console.warn(
                        `Endpoint 'list' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        return this.app;
    }
}
