// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { ServiceService } from "./api/resources/service/service/ServiceService";
import type { RootService } from "./api/service/RootService";

export function register(
    honoApp: Hono,
    services: {
        _root: RootService;
        service: ServiceService;
    },
): void {
    honoApp.route("/", services._root.toHono());
    honoApp.route("/", services.service.toHono());
}
