// This file was auto-generated by Fern from our API Definition.

import { Hono, type MiddlewareHandler } from "hono";
import { setCookie } from "hono/cookie";
import type { CookieOptions } from "hono/utils/cookie";
import * as errors from "../../../../errors/index";
import * as serializers from "../../../../serialization/index";
import type * as SeedExhaustive from "../../../index";

export interface InlinedRequestsServiceMethods {
    /**
     * POST with custom object in request body, response is an object
     */
    postWithObjectBodyandResponse(
        req: {
            body: SeedExhaustive.PostWithObjectBody;
        },
        res: {
            send: (responseBody: SeedExhaustive.types.ObjectWithOptionalField) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
}

export class InlinedRequestsService {
    private app;

    constructor(
        private readonly methods: InlinedRequestsServiceMethods,
        middleware: MiddlewareHandler[] = [],
    ) {
        this.app = new Hono();
        middleware.forEach((m) => this.app.use("*", m));
    }

    /** Adds middleware to the Hono app for all routes. */
    public addMiddleware(handler: MiddlewareHandler): this {
        this.app.use("*", handler);
        return this;
    }

    /** Returns the Hono app instance with all routes configured. */
    public toHono(): Hono {
        this.app.post("/object", async (c) => {
            const request = await c.req.json();
            if (request.ok) {
                try {
                    let _responseBody: SeedExhaustive.types.ObjectWithOptionalField | undefined;
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.postWithObjectBodyandResponse(
                        {
                            body: request.value,
                        },
                        {
                            send: async (responseBody) => {
                                _responseBody = responseBody;
                            },
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.json(
                        serializers.types.ObjectWithOptionalField.jsonOrThrow(_responseBody, {
                            unrecognizedObjectKeys: "strip",
                        }),
                        200,
                    );
                } catch (error) {
                    if (error instanceof errors.SeedExhaustiveError) {
                        switch (error.errorName) {
                            case "BadRequestBody":
                                break;
                            default:
                                console.warn(
                                    `Endpoint 'postWithObjectBodyandResponse' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                                );
                        }
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        return this.app;
    }
}
