// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { OrganizationsService } from "./api/resources/organizations/service/OrganizationsService";
import type { UserService } from "./api/resources/user/service/UserService";

export function register(
    honoApp: Hono,
    services: {
        organizations: OrganizationsService;
        user: UserService;
    },
): void {
    honoApp.route("/organizations/:organization_id", services.organizations.toHono());
    honoApp.route("/user", services.user.toHono());
}
