// This file was auto-generated by Fern from our API Definition.

import type { Context } from "hono";
import * as errors from "../../errors/index";
import * as serializers from "../../serialization/index";
import type * as SeedApi from "../index";

export class UnprocessableEntityError extends errors.SeedApiError {
    constructor(private readonly body: SeedApi.PlainObject) {
        super("UnprocessableEntityError");
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = this.constructor.name;
    }

    public toResponse(c: Context): Response {
        return c.json(serializers.PlainObject.jsonOrThrow(this.body, { unrecognizedObjectKeys: "strip" }), 422);
    }
}
