// This file was auto-generated by Fern from our API Definition.

import { Hono, type MiddlewareHandler } from "hono";
import { setCookie } from "hono/cookie";
import type { CookieOptions } from "hono/utils/cookie";
import * as errors from "../../../../errors/index";

export interface BasicAuthServiceMethods {
    /**
     * GET request with basic auth scheme
     */
    getWithBasicAuth(
        req: {},
        res: {
            send: (responseBody: boolean) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    /**
     * POST request with basic auth scheme
     */
    postWithBasicAuth(
        req: {
            body: unknown;
        },
        res: {
            send: (responseBody: boolean) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
}

export class BasicAuthService {
    private app;

    constructor(
        private readonly methods: BasicAuthServiceMethods,
        middleware: MiddlewareHandler[] = [],
    ) {
        this.app = new Hono();
        middleware.forEach((m) => this.app.use("*", m));
    }

    /** Adds middleware to the Hono app for all routes. */
    public addMiddleware(handler: MiddlewareHandler): this {
        this.app.use("*", handler);
        return this;
    }

    /** Returns the Hono app instance with all routes configured. */
    public toHono(): Hono {
        this.app.get("/basic-auth", async (c) => {
            try {
                let _responseBody: boolean | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.getWithBasicAuth(
                    {},
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(_responseBody, 200);
            } catch (error) {
                if (error instanceof errors.SeedBasicAuthError) {
                    switch (error.errorName) {
                        case "UnauthorizedRequest":
                            break;
                        default:
                            console.warn(
                                `Endpoint 'getWithBasicAuth' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                            );
                    }
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        this.app.post("/basic-auth", async (c) => {
            try {
                let _responseBody: boolean | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.postWithBasicAuth(
                    {
                        body: await c.req.json(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(_responseBody, 200);
            } catch (error) {
                if (error instanceof errors.SeedBasicAuthError) {
                    switch (error.errorName) {
                        case "UnauthorizedRequest":
                        case "BadRequest":
                            break;
                        default:
                            console.warn(
                                `Endpoint 'postWithBasicAuth' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                            );
                    }
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        return this.app;
    }
}
