// This file was auto-generated by Fern from our API Definition.

import type { Context } from "hono";
import * as errors from "../../../../errors/index";
import * as serializers from "../../../../serialization/index";
import type * as SeedApi from "../../../index";

export class MovieDoesNotExistError extends errors.SeedApiError {
    constructor(private readonly body: SeedApi.MovieId) {
        super("MovieDoesNotExistError");
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = this.constructor.name;
    }

    public toResponse(c: Context): Response {
        return c.json(
            serializers.MovieId.jsonOrThrow(this.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
            }),
            404,
        );
    }
}
