// This file was auto-generated by Fern from our API Definition.

import { Hono, type MiddlewareHandler } from "hono";
import { setCookie } from "hono/cookie";
import type { CookieOptions } from "hono/utils/cookie";
import * as errors from "../../../../errors/index";
import * as serializers from "../../../../serialization/index";
import type * as SeedResponseProperty from "../../../index";

export interface ServiceServiceMethods {
    getMovie(
        req: {
            body: string;
        },
        res: {
            send: (responseBody: SeedResponseProperty.Response) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    getMovieDocs(
        req: {
            body: string;
        },
        res: {
            send: (responseBody: SeedResponseProperty.Response) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    getMovieName(
        req: {
            body: string;
        },
        res: {
            send: (responseBody: SeedResponseProperty.StringResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    getMovieMetadata(
        req: {
            body: string;
        },
        res: {
            send: (responseBody: SeedResponseProperty.Response) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    getOptionalMovie(
        req: {
            body: string;
        },
        res: {
            send: (responseBody: SeedResponseProperty.Response | undefined) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    getOptionalMovieDocs(
        req: {
            body: string;
        },
        res: {
            send: (responseBody: SeedResponseProperty.OptionalWithDocs | undefined) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    getOptionalMovieName(
        req: {
            body: string;
        },
        res: {
            send: (responseBody: SeedResponseProperty.OptionalStringResponse | undefined) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
}

export class ServiceService {
    private app;

    constructor(
        private readonly methods: ServiceServiceMethods,
        middleware: MiddlewareHandler[] = [],
    ) {
        this.app = new Hono();
        middleware.forEach((m) => this.app.use("*", m));
    }

    /** Adds middleware to the Hono app for all routes. */
    public addMiddleware(handler: MiddlewareHandler): this {
        this.app.use("*", handler);
        return this;
    }

    /** Returns the Hono app instance with all routes configured. */
    public toHono(): Hono {
        this.app.post("/movie", async (c) => {
            const request = await c.req.json();
            if (request.ok) {
                try {
                    let _responseBody: SeedResponseProperty.Response | undefined;
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.getMovie(
                        {
                            body: request.value,
                        },
                        {
                            send: async (responseBody) => {
                                _responseBody = responseBody;
                            },
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.json(
                        serializers.Response.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }),
                        200,
                    );
                } catch (error) {
                    if (error instanceof errors.SeedResponsePropertyError) {
                        console.warn(
                            `Endpoint 'getMovie' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.post("/movie", async (c) => {
            const request = await c.req.json();
            if (request.ok) {
                try {
                    let _responseBody: SeedResponseProperty.Response | undefined;
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.getMovieDocs(
                        {
                            body: request.value,
                        },
                        {
                            send: async (responseBody) => {
                                _responseBody = responseBody;
                            },
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.json(
                        serializers.Response.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }),
                        200,
                    );
                } catch (error) {
                    if (error instanceof errors.SeedResponsePropertyError) {
                        console.warn(
                            `Endpoint 'getMovieDocs' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.post("/movie", async (c) => {
            const request = await c.req.json();
            if (request.ok) {
                try {
                    let _responseBody: SeedResponseProperty.StringResponse | undefined;
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.getMovieName(
                        {
                            body: request.value,
                        },
                        {
                            send: async (responseBody) => {
                                _responseBody = responseBody;
                            },
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.json(
                        serializers.StringResponse.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }),
                        200,
                    );
                } catch (error) {
                    if (error instanceof errors.SeedResponsePropertyError) {
                        console.warn(
                            `Endpoint 'getMovieName' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.post("/movie", async (c) => {
            const request = await c.req.json();
            if (request.ok) {
                try {
                    let _responseBody: SeedResponseProperty.Response | undefined;
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.getMovieMetadata(
                        {
                            body: request.value,
                        },
                        {
                            send: async (responseBody) => {
                                _responseBody = responseBody;
                            },
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.json(
                        serializers.Response.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }),
                        200,
                    );
                } catch (error) {
                    if (error instanceof errors.SeedResponsePropertyError) {
                        console.warn(
                            `Endpoint 'getMovieMetadata' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.post("/movie", async (c) => {
            const request = await c.req.json();
            if (request.ok) {
                try {
                    let _responseBody: (SeedResponseProperty.Response | undefined) | undefined;
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.getOptionalMovie(
                        {
                            body: request.value,
                        },
                        {
                            send: async (responseBody) => {
                                _responseBody = responseBody;
                            },
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.json(_responseBody, 200);
                } catch (error) {
                    if (error instanceof errors.SeedResponsePropertyError) {
                        console.warn(
                            `Endpoint 'getOptionalMovie' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.post("/movie", async (c) => {
            const request = await c.req.json();
            if (request.ok) {
                try {
                    let _responseBody: (SeedResponseProperty.OptionalWithDocs | undefined) | undefined;
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.getOptionalMovieDocs(
                        {
                            body: request.value,
                        },
                        {
                            send: async (responseBody) => {
                                _responseBody = responseBody;
                            },
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.json(
                        serializers.OptionalWithDocs.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }),
                        200,
                    );
                } catch (error) {
                    if (error instanceof errors.SeedResponsePropertyError) {
                        console.warn(
                            `Endpoint 'getOptionalMovieDocs' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.post("/movie", async (c) => {
            const request = await c.req.json();
            if (request.ok) {
                try {
                    let _responseBody: (SeedResponseProperty.OptionalStringResponse | undefined) | undefined;
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.getOptionalMovieName(
                        {
                            body: request.value,
                        },
                        {
                            send: async (responseBody) => {
                                _responseBody = responseBody;
                            },
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.json(
                        serializers.OptionalStringResponse.jsonOrThrow(_responseBody, {
                            unrecognizedObjectKeys: "strip",
                        }),
                        200,
                    );
                } catch (error) {
                    if (error instanceof errors.SeedResponsePropertyError) {
                        console.warn(
                            `Endpoint 'getOptionalMovieName' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        return this.app;
    }
}
