// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { RootService } from "./api/service/RootService";

export function register(
    honoApp: Hono,
    services: {
        _root: RootService;
    },
): void {
    honoApp.route("/root", services._root.toHono());
}
