"use strict";
// This file was auto-generated by Fern from our API Definition.
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ImdbService = void 0;
const hono_1 = require("hono");
const cookie_1 = require("hono/cookie");
const errors = __importStar(require("../../../../errors/index"));
const serializers = __importStar(require("../../../../serialization/index"));
class ImdbService {
    constructor(methods, middleware = []) {
        this.methods = methods;
        this.app = new hono_1.Hono();
        middleware.forEach((m) => this.app.use("*", m));
    }
    /** Adds middleware to the Hono app for all routes. */
    addMiddleware(handler) {
        this.app.use("*", handler);
        return this;
    }
    /** Returns the Hono app instance with all routes configured. */
    toHono() {
        this.app.post("/create-movie", (c) => __awaiter(this, void 0, void 0, function* () {
            const request = serializers.CreateMovieRequest.parse(yield c.req.json());
            if (request.ok) {
                try {
                    let _responseBody;
                    const _cookies = [];
                    yield this.methods.createMovie({
                        body: request.value,
                    }, {
                        send: (responseBody) => __awaiter(this, void 0, void 0, function* () {
                            _responseBody = responseBody;
                        }),
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    });
                    for (const cookie of _cookies) {
                        (0, cookie_1.setCookie)(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.json(serializers.MovieId.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }), 201);
                }
                catch (error) {
                    if (error instanceof errors.SeedApiError) {
                        console.warn(`Endpoint 'createMovie' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`);
                        return error.toResponse(c);
                    }
                    else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            }
            else {
                return c.json({
                    errors: request.errors.map((error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`),
                }, 422);
            }
        }));
        this.app.get("/:movieId", (c) => __awaiter(this, void 0, void 0, function* () {
            try {
                let _responseBody;
                const _cookies = [];
                yield this.methods.getMovie({
                    params: c.req.param(),
                }, {
                    send: (responseBody) => __awaiter(this, void 0, void 0, function* () {
                        _responseBody = responseBody;
                    }),
                    cookie: (name, value, options) => {
                        _cookies.push({ name, value, options });
                    },
                    locals: {},
                });
                for (const cookie of _cookies) {
                    (0, cookie_1.setCookie)(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(serializers.Movie.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }), 200);
            }
            catch (error) {
                if (error instanceof errors.SeedApiError) {
                    switch (error.errorName) {
                        case "MovieDoesNotExistError":
                            break;
                        default:
                            console.warn(`Endpoint 'getMovie' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`);
                    }
                    return error.toResponse(c);
                }
                else {
                    return c.json("Internal Server Error", 500);
                }
            }
        }));
        return this.app;
    }
}
exports.ImdbService = ImdbService;
