// This file was auto-generated by Fern from our API Definition.

import { Hono, type MiddlewareHandler } from "hono";
import { setCookie } from "hono/cookie";
import type { CookieOptions } from "hono/utils/cookie";
import * as errors from "../../../../errors/index";
import * as serializers from "../../../../serialization/index";
import type * as SeedRequestParameters from "../../../index";

export interface UserServiceMethods {
    createUsername(
        req: {
            query: {
                tags: string[];
            };
            body: SeedRequestParameters.CreateUsernameRequest;
        },
        res: {
            send: () => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    createUsernameWithReferencedType(
        req: {
            query: {
                tags: string[];
            };
            body: SeedRequestParameters.CreateUsernameBody;
        },
        res: {
            send: () => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    createUsernameOptional(
        req: {
            body: (SeedRequestParameters.CreateUsernameBodyOptionalProperties | null) | undefined;
        },
        res: {
            send: () => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    getUsername(
        req: {
            query: {
                limit: number;
                id: string;
                date: string;
                deadline: Date;
                bytes: string;
                user: SeedRequestParameters.User;
                userList: SeedRequestParameters.User[];
                optionalDeadline?: Date;
                keyValue: Record<string, string>;
                optionalString?: string;
                nestedUser: SeedRequestParameters.NestedUser;
                optionalUser?: SeedRequestParameters.User;
                excludeUser: SeedRequestParameters.User;
                filter: string;
                longParam: number;
                bigIntParam: string;
            };
        },
        res: {
            send: (responseBody: SeedRequestParameters.User) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
}

export class UserService {
    private app;

    constructor(
        private readonly methods: UserServiceMethods,
        middleware: MiddlewareHandler[] = [],
    ) {
        this.app = new Hono();
        middleware.forEach((m) => this.app.use("*", m));
    }

    /** Adds middleware to the Hono app for all routes. */
    public addMiddleware(handler: MiddlewareHandler): this {
        this.app.use("*", handler);
        return this;
    }

    /** Returns the Hono app instance with all routes configured. */
    public toHono(): Hono {
        this.app.post("/username", async (c) => {
            const request = await c.req.json();
            if (request.ok) {
                try {
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.createUsername(
                        {
                            query: c.req.query(),
                            body: request.value,
                        },
                        {
                            send: async () => {},
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.text("", 204);
                } catch (error) {
                    if (error instanceof errors.SeedRequestParametersError) {
                        console.warn(
                            `Endpoint 'createUsername' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.post("/username-referenced", async (c) => {
            const request = serializers.CreateUsernameBody.parse(await c.req.json());
            if (request.ok) {
                try {
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.createUsernameWithReferencedType(
                        {
                            query: c.req.query(),
                            body: request.value,
                        },
                        {
                            send: async () => {},
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.text("", 204);
                } catch (error) {
                    if (error instanceof errors.SeedRequestParametersError) {
                        console.warn(
                            `Endpoint 'createUsernameWithReferencedType' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.post("/username-optional", async (c) => {
            const request = await c.req.json();
            if (request.ok) {
                try {
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.createUsernameOptional(
                        {
                            body: request.value,
                        },
                        {
                            send: async () => {},
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.text("", 204);
                } catch (error) {
                    if (error instanceof errors.SeedRequestParametersError) {
                        console.warn(
                            `Endpoint 'createUsernameOptional' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.get("", async (c) => {
            try {
                let _responseBody: SeedRequestParameters.User | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.getUsername(
                    {
                        query: c.req.query(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(serializers.User.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }), 200);
            } catch (error) {
                if (error instanceof errors.SeedRequestParametersError) {
                    console.warn(
                        `Endpoint 'getUsername' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        return this.app;
    }
}
