// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { AuthService } from "./api/resources/auth/service/AuthService";
import type { UserService } from "./api/resources/user/service/UserService";

export function register(
    honoApp: Hono,
    services: {
        auth: AuthService;
        user: UserService;
    },
): void {
    honoApp.route("/", services.auth.toHono());
    honoApp.route("", services.user.toHono());
}
