// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { ImdbService } from "./api/resources/imdb/service/ImdbService";

export function register(
    honoApp: Hono,
    services: {
        imdb: ImdbService;
    },
): void {
    honoApp.route("/movies", services.imdb.toHono());
}
