// This file was auto-generated by Fern from our API Definition.

import type { Context } from "hono";
import * as errors from "../../../../errors/index";
import * as serializers from "../../../../serialization/index";
import type * as SeedErrorProperty from "../../../index";

export class PropertyBasedErrorTest extends errors.SeedErrorPropertyError {
    constructor(private readonly body: SeedErrorProperty.PropertyBasedErrorTestBody) {
        super("PropertyBasedErrorTest");
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = this.constructor.name;
    }

    public toResponse(c: Context): Response {
        return c.json(
            serializers.PropertyBasedErrorTestBody.jsonOrThrow(this.body, { unrecognizedObjectKeys: "strip" }),
            400,
        );
    }
}
