// This file was auto-generated by Fern from our API Definition.

import { Hono, type MiddlewareHandler } from "hono";
import { setCookie } from "hono/cookie";
import type { CookieOptions } from "hono/utils/cookie";
import * as errors from "../../../../errors/index";
import * as serializers from "../../../../serialization/index";
import type * as SeedMixedCase from "../../../index";

export interface ServiceServiceMethods {
    getResource(
        req: {
            params: {
                ResourceID: string;
            };
        },
        res: {
            send: (responseBody: SeedMixedCase.Resource) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    listResources(
        req: {
            query: {
                page_limit: number;
                beforeDate: string;
            };
        },
        res: {
            send: (responseBody: SeedMixedCase.Resource[]) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
}

export class ServiceService {
    private app;

    constructor(
        private readonly methods: ServiceServiceMethods,
        middleware: MiddlewareHandler[] = [],
    ) {
        this.app = new Hono();
        middleware.forEach((m) => this.app.use("*", m));
    }

    /** Adds middleware to the Hono app for all routes. */
    public addMiddleware(handler: MiddlewareHandler): this {
        this.app.use("*", handler);
        return this;
    }

    /** Returns the Hono app instance with all routes configured. */
    public toHono(): Hono {
        this.app.get("/:ResourceID", async (c) => {
            try {
                let _responseBody: SeedMixedCase.Resource | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.getResource(
                    {
                        params: c.req.param(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(
                    serializers.Resource.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }),
                    200,
                );
            } catch (error) {
                if (error instanceof errors.SeedMixedCaseError) {
                    console.warn(
                        `Endpoint 'getResource' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        this.app.get("", async (c) => {
            try {
                let _responseBody: SeedMixedCase.Resource[] | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.listResources(
                    {
                        query: c.req.query(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(_responseBody, 200);
            } catch (error) {
                if (error instanceof errors.SeedMixedCaseError) {
                    console.warn(
                        `Endpoint 'listResources' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        return this.app;
    }
}
