// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { ContainerService as endpoints_ContainerService } from "./api/resources/endpoints/resources/container/service/ContainerService";
import type { ContentTypeService as endpoints_ContentTypeService } from "./api/resources/endpoints/resources/contentType/service/ContentTypeService";
import type { EnumService as endpoints_EnumService } from "./api/resources/endpoints/resources/enum/service/EnumService";
import type { HttpMethodsService as endpoints_HttpMethodsService } from "./api/resources/endpoints/resources/httpMethods/service/HttpMethodsService";
import type { ObjectService as endpoints_ObjectService } from "./api/resources/endpoints/resources/object/service/ObjectService";
import type { ParamsService as endpoints_ParamsService } from "./api/resources/endpoints/resources/params/service/ParamsService";
import type { PrimitiveService as endpoints_PrimitiveService } from "./api/resources/endpoints/resources/primitive/service/PrimitiveService";
import type { PutService as endpoints_PutService } from "./api/resources/endpoints/resources/put/service/PutService";
import type { UnionService as endpoints_UnionService } from "./api/resources/endpoints/resources/union/service/UnionService";
import type { UrlsService as endpoints_UrlsService } from "./api/resources/endpoints/resources/urls/service/UrlsService";
import type { InlinedRequestsService } from "./api/resources/inlinedRequests/service/InlinedRequestsService";
import type { NoAuthService } from "./api/resources/noAuth/service/NoAuthService";
import type { NoReqBodyService } from "./api/resources/noReqBody/service/NoReqBodyService";
import type { ReqWithHeadersService } from "./api/resources/reqWithHeaders/service/ReqWithHeadersService";

export function register(
    honoApp: Hono,
    services: {
        inlinedRequests: InlinedRequestsService;
        noAuth: NoAuthService;
        noReqBody: NoReqBodyService;
        reqWithHeaders: ReqWithHeadersService;
        endpoints: {
            container: endpoints_ContainerService;
            contentType: endpoints_ContentTypeService;
            enum: endpoints_EnumService;
            httpMethods: endpoints_HttpMethodsService;
            object: endpoints_ObjectService;
            params: endpoints_ParamsService;
            primitive: endpoints_PrimitiveService;
            put: endpoints_PutService;
            union: endpoints_UnionService;
            urls: endpoints_UrlsService;
        };
    },
): void {
    honoApp.route("/container", services.endpoints.container.toHono());
    honoApp.route("/foo", services.endpoints.contentType.toHono());
    honoApp.route("/enum", services.endpoints.enum.toHono());
    honoApp.route("/http-methods", services.endpoints.httpMethods.toHono());
    honoApp.route("/object", services.endpoints.object.toHono());
    honoApp.route("/params", services.endpoints.params.toHono());
    honoApp.route("/primitive", services.endpoints.primitive.toHono());
    honoApp.route("", services.endpoints.put.toHono());
    honoApp.route("/union", services.endpoints.union.toHono());
    honoApp.route("/urls", services.endpoints.urls.toHono());
    honoApp.route("/req-bodies", services.inlinedRequests.toHono());
    honoApp.route("/no-auth", services.noAuth.toHono());
    honoApp.route("/no-req-body", services.noReqBody.toHono());
    honoApp.route("/test-headers", services.reqWithHeaders.toHono());
}
