// This file was auto-generated by Fern from our API Definition.

import { Hono, type MiddlewareHandler } from "hono";
import { setCookie } from "hono/cookie";
import type { CookieOptions } from "hono/utils/cookie";
import * as errors from "../../../../errors/index";
import * as serializers from "../../../../serialization/index";
import type * as SeedApi from "../../../index";

export interface ImdbServiceMethods {
    /**
     * Add a movie to the database using the movies/* /... path.
     */
    createMovie(
        req: {
            body: SeedApi.CreateMovieRequest;
        },
        res: {
            send: (responseBody: SeedApi.MovieId) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    getMovie(
        req: {
            params: {
                movieId: serializers.MovieId.Raw;
            };
        },
        res: {
            send: (responseBody: SeedApi.Movie) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
}

export class ImdbService {
    private app;

    constructor(
        private readonly methods: ImdbServiceMethods,
        middleware: MiddlewareHandler[] = [],
    ) {
        this.app = new Hono();
        middleware.forEach((m) => this.app.use("*", m));
    }

    /** Adds middleware to the Hono app for all routes. */
    public addMiddleware(handler: MiddlewareHandler): this {
        this.app.use("*", handler);
        return this;
    }

    /** Returns the Hono app instance with all routes configured. */
    public toHono(): Hono {
        this.app.post("/create-movie", async (c) => {
            const request = serializers.CreateMovieRequest.parse(await c.req.json());
            if (request.ok) {
                try {
                    let _responseBody: SeedApi.MovieId | undefined;
                    const _cookies: {
                        name: string;
                        value: string;
                        options?: CookieOptions;
                    }[] = [];
                    await this.methods.createMovie(
                        {
                            body: request.value,
                        },
                        {
                            send: async (responseBody) => {
                                _responseBody = responseBody;
                            },
                            cookie: (name, value, options) => {
                                _cookies.push({ name, value, options });
                            },
                            locals: {},
                        },
                    );
                    for (const cookie of _cookies) {
                        setCookie(c, cookie.name, cookie.value, cookie.options);
                    }
                    return c.json(
                        serializers.MovieId.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }),
                        201,
                    );
                } catch (error) {
                    if (error instanceof errors.SeedApiError) {
                        console.warn(
                            `Endpoint 'createMovie' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        return error.toResponse(c);
                    } else {
                        return c.json("Internal Server Error", 500);
                    }
                }
            } else {
                return c.json(
                    {
                        errors: request.errors.map(
                            (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                        ),
                    },
                    422,
                );
            }
        });
        this.app.get("/:movieId", async (c) => {
            try {
                let _responseBody: SeedApi.Movie | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.getMovie(
                    {
                        params: c.req.param(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(serializers.Movie.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }), 200);
            } catch (error) {
                if (error instanceof errors.SeedApiError) {
                    switch (error.errorName) {
                        case "MovieDoesNotExistError":
                            break;
                        default:
                            console.warn(
                                `Endpoint 'getMovie' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                            );
                    }
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        return this.app;
    }
}
