// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { BigunionService } from "./api/resources/bigunion/service/BigunionService";
import type { UnionService } from "./api/resources/union/service/UnionService";

export function register(
    honoApp: Hono,
    services: {
        bigunion: BigunionService;
        union: UnionService;
    },
): void {
    honoApp.route("/", services.bigunion.toHono());
    honoApp.route("/", services.union.toHono());
}
