// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { TestGroupService } from "./api/resources/testGroup/service/TestGroupService";

export function register(
    honoApp: Hono,
    services: {
        testGroup: TestGroupService;
    },
): void {
    honoApp.route("", services.testGroup.toHono());
}
