// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { BService as a_b_RootService } from "./api/resources/a/resources/b/service/BService";
import type { CService as a_c_RootService } from "./api/resources/a/resources/c/service/CService";
import type { ServiceService as folder_ServiceService } from "./api/resources/folder/resources/service/service/ServiceService";
import type { FolderService as folder_RootService } from "./api/resources/folder/service/FolderService";
import type { RootService } from "./api/service/RootService";

export function register(
    honoApp: Hono,
    services: {
        _root: RootService;
        a: {
            b: {
                _root: a_b_RootService;
            };
            c: {
                _root: a_c_RootService;
            };
        };
        folder: {
            _root: folder_RootService;
            service: folder_ServiceService;
        };
    },
): void {
    honoApp.route("/", services._root.toHono());
    honoApp.route("/", services.a.b._root.toHono());
    honoApp.route("/", services.a.c._root.toHono());
    honoApp.route("/", services.folder._root.toHono());
    honoApp.route("/service", services.folder.service.toHono());
}
