// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { AuthService as auth_RootService } from "./api/resources/auth/service/AuthService";
import type { ApiService as nested_ApiService } from "./api/resources/nested/resources/api/service/ApiService";
import type { ApiService as nestedNoAuth_ApiService } from "./api/resources/nestedNoAuth/resources/api/service/ApiService";
import type { SimpleService } from "./api/resources/simple/service/SimpleService";

export function register(
    honoApp: Hono,
    services: {
        simple: SimpleService;
        auth: {
            _root: auth_RootService;
        };
        nestedNoAuth: {
            api: nestedNoAuth_ApiService;
        };
        nested: {
            api: nested_ApiService;
        };
    },
): void {
    honoApp.route("/", services.auth._root.toHono());
    honoApp.route("/nested-no-auth", services.nestedNoAuth.api.toHono());
    honoApp.route("/nested", services.nested.api.toHono());
    honoApp.route("/", services.simple.toHono());
}
