// This file was auto-generated by Fern from our API Definition.

import { Hono, type MiddlewareHandler } from "hono";
import { setCookie } from "hono/cookie";
import type { CookieOptions } from "hono/utils/cookie";
import * as errors from "../../../../errors/index";
import * as serializers from "../../../../serialization/index";
import type * as SeedLiteral from "../../../index";

export interface QueryServiceMethods {
    send(
        req: {
            query: {
                prompt: "You are a helpful assistant";
                optional_prompt?: "You are a helpful assistant";
                alias_prompt: SeedLiteral.AliasToPrompt;
                alias_optional_prompt?: SeedLiteral.AliasToPrompt;
                query: string;
                stream: false;
                optional_stream?: false;
                alias_stream: SeedLiteral.AliasToStream;
                alias_optional_stream?: SeedLiteral.AliasToStream;
            };
        },
        res: {
            send: (responseBody: SeedLiteral.SendResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
}

export class QueryService {
    private app;

    constructor(
        private readonly methods: QueryServiceMethods,
        middleware: MiddlewareHandler[] = [],
    ) {
        this.app = new Hono();
        middleware.forEach((m) => this.app.use("*", m));
    }

    /** Adds middleware to the Hono app for all routes. */
    public addMiddleware(handler: MiddlewareHandler): this {
        this.app.use("*", handler);
        return this;
    }

    /** Returns the Hono app instance with all routes configured. */
    public toHono(): Hono {
        this.app.post("/query", async (c) => {
            try {
                let _responseBody: SeedLiteral.SendResponse | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.send(
                    {
                        query: c.req.query(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(
                    serializers.SendResponse.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }),
                    200,
                );
            } catch (error) {
                if (error instanceof errors.SeedLiteralError) {
                    console.warn(
                        `Endpoint 'send' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        return this.app;
    }
}
