// This file was auto-generated by Fern from our API Definition.

import { Hono, type MiddlewareHandler } from "hono";
import { setCookie } from "hono/cookie";
import type { CookieOptions } from "hono/utils/cookie";
import * as errors from "../../errors/index";
import * as serializers from "../../serialization/index";
import type * as SeedApi from "../index";

export interface RootServiceMethods {
    search(
        req: {
            query: {
                limit: number;
                id: string;
                date: string;
                deadline: Date;
                bytes: string;
                user: SeedApi.User;
                userList?: SeedApi.User;
                optionalDeadline?: Date;
                keyValue?: Record<string, string>;
                optionalString?: string;
                nestedUser?: SeedApi.NestedUser;
                optionalUser?: SeedApi.User;
                excludeUser?: SeedApi.User;
                filter?: string;
                neighbor?: SeedApi.SearchRequestNeighbor;
                neighborRequired: SeedApi.SearchRequestNeighborRequired;
            };
        },
        res: {
            send: (responseBody: SeedApi.SearchResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
}

export class RootService {
    private app;

    constructor(
        private readonly methods: RootServiceMethods,
        middleware: MiddlewareHandler[] = [],
    ) {
        this.app = new Hono();
        middleware.forEach((m) => this.app.use("*", m));
    }

    /** Adds middleware to the Hono app for all routes. */
    public addMiddleware(handler: MiddlewareHandler): this {
        this.app.use("*", handler);
        return this;
    }

    /** Returns the Hono app instance with all routes configured. */
    public toHono(): Hono {
        this.app.get("/user/getUsername", async (c) => {
            try {
                let _responseBody: SeedApi.SearchResponse | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.search(
                    {
                        query: c.req.query(),
                    },
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(
                    serializers.SearchResponse.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }),
                    200,
                );
            } catch (error) {
                if (error instanceof errors.SeedApiError) {
                    console.warn(
                        `Endpoint 'search' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        return this.app;
    }
}
