// This file was auto-generated by Fern from our API Definition.

import { Hono, type MiddlewareHandler } from "hono";
import { setCookie } from "hono/cookie";
import type { CookieOptions } from "hono/utils/cookie";
import * as errors from "../../errors/index";
import * as serializers from "../../serialization/index";
import type * as SeedUndiscriminatedUnionWithResponseProperty from "../index";

export interface RootServiceMethods {
    getUnion(
        req: {},
        res: {
            send: (responseBody: SeedUndiscriminatedUnionWithResponseProperty.UnionResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
    listUnions(
        req: {},
        res: {
            send: (responseBody: SeedUndiscriminatedUnionWithResponseProperty.UnionListResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: CookieOptions) => void;
            locals: any;
        },
    ): void | Promise<void>;
}

export class RootService {
    private app;

    constructor(
        private readonly methods: RootServiceMethods,
        middleware: MiddlewareHandler[] = [],
    ) {
        this.app = new Hono();
        middleware.forEach((m) => this.app.use("*", m));
    }

    /** Adds middleware to the Hono app for all routes. */
    public addMiddleware(handler: MiddlewareHandler): this {
        this.app.use("*", handler);
        return this;
    }

    /** Returns the Hono app instance with all routes configured. */
    public toHono(): Hono {
        this.app.get("/union", async (c) => {
            try {
                let _responseBody: SeedUndiscriminatedUnionWithResponseProperty.UnionResponse | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.getUnion(
                    {},
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(
                    serializers.UnionResponse.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }),
                    200,
                );
            } catch (error) {
                if (error instanceof errors.SeedUndiscriminatedUnionWithResponsePropertyError) {
                    console.warn(
                        `Endpoint 'getUnion' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        this.app.get("/unions", async (c) => {
            try {
                let _responseBody: SeedUndiscriminatedUnionWithResponseProperty.UnionListResponse | undefined;
                const _cookies: {
                    name: string;
                    value: string;
                    options?: CookieOptions;
                }[] = [];
                await this.methods.listUnions(
                    {},
                    {
                        send: async (responseBody) => {
                            _responseBody = responseBody;
                        },
                        cookie: (name, value, options) => {
                            _cookies.push({ name, value, options });
                        },
                        locals: {},
                    },
                );
                for (const cookie of _cookies) {
                    setCookie(c, cookie.name, cookie.value, cookie.options);
                }
                return c.json(
                    serializers.UnionListResponse.jsonOrThrow(_responseBody, { unrecognizedObjectKeys: "strip" }),
                    200,
                );
            } catch (error) {
                if (error instanceof errors.SeedUndiscriminatedUnionWithResponsePropertyError) {
                    console.warn(
                        `Endpoint 'listUnions' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    return error.toResponse(c);
                } else {
                    return c.json("Internal Server Error", 500);
                }
            }
        });
        return this.app;
    }
}
