// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { NullableService } from "./api/resources/nullable/service/NullableService";

export function register(
    honoApp: Hono,
    services: {
        nullable: NullableService;
    },
): void {
    honoApp.route("/users", services.nullable.toHono());
}
