// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { DummyService } from "./api/resources/dummy/service/DummyService";

export function register(
    honoApp: Hono,
    services: {
        dummy: DummyService;
    },
): void {
    honoApp.route("", services.dummy.toHono());
}
