// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { HeadersService } from "./api/resources/headers/service/HeadersService";
import type { InlinedService } from "./api/resources/inlined/service/InlinedService";
import type { PathService } from "./api/resources/path/service/PathService";
import type { QueryService } from "./api/resources/query/service/QueryService";
import type { ReferenceService } from "./api/resources/reference/service/ReferenceService";

export function register(
    honoApp: Hono,
    services: {
        headers: HeadersService;
        inlined: InlinedService;
        path: PathService;
        query: QueryService;
        reference: ReferenceService;
    },
): void {
    honoApp.route("", services.headers.toHono());
    honoApp.route("", services.inlined.toHono());
    honoApp.route("", services.path.toHono());
    honoApp.route("", services.query.toHono());
    honoApp.route("", services.reference.toHono());
}
