// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { OptionalService } from "./api/resources/optional/service/OptionalService";

export function register(
    honoApp: Hono,
    services: {
        optional: OptionalService;
    },
): void {
    honoApp.route("", services.optional.toHono());
}
