// This file was auto-generated by Fern from our API Definition.

import type { Hono } from "hono";
import type { ServiceService as file_notification_ServiceService } from "./api/resources/file/resources/notification/resources/service/service/ServiceService";
import type { ServiceService as file_ServiceService } from "./api/resources/file/resources/service/service/ServiceService";
import type { ServiceService as health_ServiceService } from "./api/resources/health/resources/service/service/ServiceService";
import type { ServiceService } from "./api/resources/service/service/ServiceService";
import type { RootService } from "./api/service/RootService";

export function register(
    honoApp: Hono,
    services: {
        _root: RootService;
        service: ServiceService;
        file: {
            service: file_ServiceService;
            notification: {
                service: file_notification_ServiceService;
            };
        };
        health: {
            service: health_ServiceService;
        };
    },
): void {
    honoApp.route("/", services._root.toHono());
    honoApp.route("/file/notification/:notificationId", services.file.notification.service.toHono());
    honoApp.route("/file", services.file.service.toHono());
    honoApp.route("/", services.health.service.toHono());
    honoApp.route("/", services.service.toHono());
}
